# Generated by Django 2.2.6 on 2019-10-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_auto_20191014_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiphyConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('api_key', models.TextField(unique=True)),
                ('search_path', models.TextField(unique=True)),
                ('search_query', models.TextField(unique=True)),
                ('search_offset', models.IntegerField(unique=True)),
                ('search_limit', models.IntegerField(unique=True)),
            ],
        ),
    ]
