# Generated by Django 2.2.6 on 2019-10-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_giphyconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiphyConfiguration',
        ),
    ]
